name: Bug Debug Request
description: Track symptom, reproduction and acceptance criteria in one place.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: symptom
    attributes:
      label: Symptom
      description: What is broken right now?
    validations:
      required: true

  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs actual
      description: What did you expect and what happened instead?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      description: Provide deterministic reproduction steps.
      placeholder: |
        1. Go to...
        2. Click...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs/snapshots
      description: Include console logs and search snapshots (if applicable).

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What must be true for this issue to be done?
    validations:
      required: true
